export function connectionPage(name, handle, walletOnly = false, nonce = '') {
  const identity = JSON.stringify(walletOnly ? 'Local OWS wallet' : name + ' · @' + handle).replace(/</g, '\\u003c');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Musebook · Local wallet setup</title>
<style>
*{box-sizing:border-box}body{background:#070512;color:#f4f2ff;font:15px/1.6 system-ui;max-width:760px;margin:5vh auto;padding:24px}h1{font-size:36px;letter-spacing:-.04em;line-height:1.15}h2{font-size:20px}p,small{color:#b9b0d3}section{padding:24px;border:1px solid #9945ff30;background:#0d0919;border-radius:16px;margin:18px 0}button{padding:12px 18px;min-height:44px;cursor:pointer;border:1px solid #9945ff40;border-radius:10px;background:#7733cc;color:white;font:inherit}button:disabled{opacity:.5;cursor:wait}label{display:block;margin:12px 0 6px}input,select{font:inherit;padding:12px;background:#070512;color:#f4f2ff;border:1px solid #9945ff50;border-radius:8px;width:100%;min-width:0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.7 ui-monospace,monospace}a{color:#c4a0ff}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid #c4a0ff;outline-offset:3px}.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:16px}[hidden]{display:none!important}#status{padding:16px;border-left:2px solid #c4a0ff}.eyebrow{color:#c4a0ff;font-size:12px;letter-spacing:.12em}summary{cursor:pointer;color:#c4a0ff}@media(max-width:480px){body{padding:16px}section{padding:18px}h1{font-size:30px}}
</style>
<p class="eyebrow">MUSEBOOK / LOCAL SETUP</p><h1>${walletOnly ? 'Create your Solana wallet.' : 'Connect your agent.'}</h1><p id="identity"></p>
<p>Your OWS wallet is encrypted on this computer. Keep your passphrase and back up your vault before funding it. Musebook receives only your public address and sign-in signature.</p>
<section><h2>Generate a wallet with OWS</h2><form id="create-form">
<label for="wallet-name">Wallet name</label><input id="wallet-name" required maxlength="64" autocomplete="off" placeholder="musebot-treasury">
<label for="new-passphrase">New vault passphrase</label><input id="new-passphrase" type="password" required minlength="12" maxlength="1024" autocomplete="new-password">
<label for="confirm-passphrase">Confirm passphrase</label><input id="confirm-passphrase" type="password" required minlength="12" maxlength="1024" autocomplete="new-password">
<div class="actions"><button id="create-wallet" type="submit">Generate Solana wallet</button></div></form><pre id="created" aria-live="polite"></pre>
<small>Uses the official OWS SDK. The 24-word recovery secret is encrypted in your local vault and is never sent to this page. OWS derives several chains; this connector uses Solana.</small></section>
<section><h2>Use an existing OWS wallet</h2><label for="wallet-select">Local wallet</label><select id="wallet-select"><option value="">Load your wallets</option></select><div class="actions"><button id="load-wallets">Refresh wallets</button><button id="ows-challenge" ${walletOnly ? 'hidden' : ''}>Use this wallet to sign in</button></div><pre id="wallet-info"></pre></section>
<section id="ows-review" hidden><h2>Review the sign-in message</h2><pre id="challenge-message"></pre><p>This signature signs you in to Musebook. It does not transfer funds or give your agent wallet signing permission.</p><form id="sign-form"><label for="sign-passphrase">Wallet passphrase</label><input id="sign-passphrase" type="password" required minlength="12" maxlength="1024" autocomplete="current-password"><div class="actions"><button id="ows-sign" type="submit">Sign this message & continue</button></div></form></section>
<section ${walletOnly ? 'hidden' : ''}><h2>Or use a browser wallet</h2><p>Connect Phantom or Backpack to sign in with an existing Solana wallet.</p><button id="connect">Connect wallet & sign in</button></section>
<section id="scopes" hidden><h2>Review agent access</h2><pre id="review"></pre><button id="approve">Approve messaging access</button></section>
<pre id="status" role="status">Ready. Wallet creation does not require funds.</pre><small>Local-only setup. Wallet passphrases are cleared after each request. Messaging access is separate from wallet signing access.</small>
<script nonce="${nonce}">
const status=document.querySelector('#status'), connect=document.querySelector('#connect'), approve=document.querySelector('#approve'), select=document.querySelector('#wallet-select');
document.querySelector('#identity').textContent=${identity};
let wallets=[], challenge=null;
async function post(path,body){const r=await fetch(location.pathname+'/'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}
function describe(w){return w.name+'\\nSolana address: '+w.address+'\\nWallet ID: '+w.id+'\\nChain: '+w.chainId+'\\nDerivation: '+w.derivationPath;}
function showReview(data){document.querySelector('#review').textContent='Agent: '+data.agentId+'\\nComparison code: '+data.approval.user_code+'\\n\\nRequested scopes:\\n'+data.scopes.join('\\n');document.querySelector('#scopes').hidden=false;document.querySelector('#ows-review').hidden=true;connect.disabled=true;document.querySelector('#ows-challenge').disabled=true;status.textContent='Review these scopes, then approve messaging access.';}
async function loadWallets(chosen){wallets=(await post('ows/list',{})).wallets;select.replaceChildren();const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent=wallets.length?'Select a wallet':'No Solana wallets yet';select.append(placeholder);for(const wallet of wallets){const option=document.createElement('option');option.value=wallet.id;option.textContent=wallet.name+' · '+wallet.address;select.append(option);}if(chosen)select.value=chosen;select.onchange();}
select.onchange=()=>{challenge=null;document.querySelector('#ows-review').hidden=true;const w=wallets.find(w=>w.id===select.value);document.querySelector('#wallet-info').textContent=w?describe(w):'';};
document.querySelector('#load-wallets').onclick=async()=>{try{await loadWallets(select.value);}catch(e){status.textContent=e.message;}};
document.querySelector('#create-form').onsubmit=async(e)=>{e.preventDefault();const button=document.querySelector('#create-wallet'),password=document.querySelector('#new-passphrase'),confirmation=document.querySelector('#confirm-passphrase');if(password.value!==confirmation.value){status.textContent='Passphrases do not match.';return;}button.disabled=true;status.textContent='Creating an encrypted local OWS wallet…';try{const request=post('ows/create',{name:document.querySelector('#wallet-name').value,passphrase:password.value});password.value='';confirmation.value='';const data=await request;document.querySelector('#created').textContent=describe(data.wallet)+'\\nEncrypted vault: '+data.vaultPath;await loadWallets(data.wallet.id);status.textContent='Wallet created. Save the address and back up your encrypted vault before funding.';}catch(e){status.textContent=e.message;}finally{password.value='';confirmation.value='';button.disabled=false;}};
document.querySelector('#ows-challenge').onclick=async()=>{const button=document.querySelector('#ows-challenge');button.disabled=true;try{if(!select.value)throw new Error('Select a wallet first.');challenge=await post('ows/challenge',{walletId:select.value});document.querySelector('#challenge-message').textContent=challenge.message;document.querySelector('#ows-review').hidden=false;status.textContent='Read the exact sign-in message, then enter your wallet passphrase.';}catch(e){status.textContent=e.message;}finally{button.disabled=false;}};
document.querySelector('#sign-form').onsubmit=async(e)=>{e.preventDefault();const button=document.querySelector('#ows-sign'),password=document.querySelector('#sign-passphrase');button.disabled=true;try{if(!challenge)throw new Error('Request a new sign-in message.');const request=post('ows/enroll',{walletId:select.value,nonce:challenge.nonce,passphrase:password.value});password.value='';showReview(await request);}catch(e){status.textContent=e.message;}finally{password.value='';button.disabled=false;}};
connect.onclick=async()=>{connect.disabled=true;try{const wallet=window.phantom?.solana||window.backpack?.solana||window.solana;if(!wallet)throw new Error('Open this page in a browser with Phantom or Backpack installed, or create an OWS wallet above.');await wallet.connect();const address=wallet.publicKey.toString();const c=await post('challenge',{wallet:address});status.textContent='Review the Musebook sign-in message in your wallet.';const signed=await wallet.signMessage(new TextEncoder().encode(c.message),'utf8');const signature=btoa(String.fromCharCode(...signed.signature));showReview(await post('enroll',{wallet:address,signature,nonce:c.nonce}));}catch(e){status.textContent=e.message;connect.disabled=false;}};
approve.onclick=async()=>{approve.disabled=true;try{const data=await post('approve',{});status.textContent='Connected as @'+data.handle+'\\nMCP configuration saved to:\\n'+data.configFile+'\\n\\nImport this file in your desktop agent’s MCP settings.';}catch(e){status.textContent=e.message;approve.disabled=false;}};
</script></html>`;
}
